### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by perimosocordiae**
This is where I got for tonight. The first test still isn't passing, but it's not obviously failing as hard as it used to.

### CODE REVIEW

**Comment by perimosocordiae** [comment]
As of the last commit, I now have all 6 tests passing! My platform details from pytest are:
```
platform darwin -- Python 3.6.0, pytest-3.0.3, py-1.4.32, pluggy-0.4.0
```

This PR introduces two new dependencies:
 * `six` allows the same codebase to run on Python2 and Python3 with minimal hassle
 * `pdfminer.six` is a 2/3-compatible fork of the Python2-only `pdfminer` library

**Comment by jsaponara** [comment]
Hey CJ, that's amazing, thanks for your work!  While ensuring that the code still works with py27 I saw that the 2 script tests (as opposed to the 4 api tests) fail only due to differences between non-ascii characters in f1040-fmt.xml.  This difference seems to arise not from your changes but from the new pdfminer.six.  This is not a show-stopper, though I did notice that the pdfminer produces characters more faithful to the original pdf:

pdf: For the year Jan. 1–Dec. 31, 2016  [that hypenoid is an 8211]
pdfminer: For the year Jan. 1&#8211;Dec. 31
pdfminer.six: For the year Jan. 1&#226;&#128;&#147;Dec. 31

I do some substitutions based on these higher characters which I'd need to review.  Oddly pdfminer.six must be generating the 8211 under py3 or the tests wouldn't pass.

I was wondering if my cluttered venv was affecting anything, so I did a completely fresh venv/install and surprisingly got the dumppdf.py import error below.  This is clearly not due to your changes but gives me pause.  I really value your patch, but for now I propose to merge it into its own branch, only merging into master when these issues are resolved.  This would allow others to try your branch and determine if it works only in your env or is broken only in mine!  Ideally it can be made to work everywhere.  Before I do this merge-to-new-branch, I invite your comments.

Warmest thanks, John

ERROR:f1040:run: command [dumppdf.py -at /home/john/dev/tax/tex/six/opentaxforms/test/forms_1040_full/f1040.pdf >
 /home/john/dev/tax/tex/six/opentaxforms/test/forms_1040_full/f1040.xml] returned error [Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 545, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 237, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 582, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 528, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 412, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_nd import *
ImportError: No module named _sysconfigdata_nd] and output []

**Comment by perimosocordiae** [comment]
Thanks for taking a look! I agree that this isn't ready to merge to master yet.

I tried running `dumppdf.py -at test/forms_1040_full/f1040.pdf`, using both the python3 install and the python2 install of pdfminer.six. Neither gave me any errors, and both produced this output for the part you mentioned:
```
For the year Jan. 1&#92;226Dec. 31, 2015
```

Looking at your traceback, it seems like your virtualenvironment is somehow broken. No idea how, though.

**Comment by jsaponara** [comment]
In an uncorrupted virtualenv, py27 worked fine and py34 worked [but for a few unicode chars in f1040-fmt.xml in the xfa test] with a couple minor changes [relaxing version of argparse in setup.py and changing 'w' to 'wb' in extractFillableFields.py].  If these latter tweaks cause your py36 trouble, let me know.  Thanks again CJ!  On to your other PRs!

**Pull request merged**
